### ISSUE TITLE
How to install the vex-hugo?

### ISSUE THREAD

**Issue by 13479776** [themefisher/vex-hugo#10]
Hi sir or madam,

   I download the vex-hugo and use the themes. However, there were nothing after i run the code "hugo server --theme=vex-hugo —buildDrafts".

   if i should install the  Bootstrap 4 before the vex-hugo applied. i don't know how to install or use this themes. Could you please give some detailed guide or code for MAC?

Thanks 
Hemi

**Comment by themefisherDev** [comment]
clone the template on your mac. open terminal on this clone folder, and run `cd exampleSite/ && hugo server --themesDir ../..`
