### ISSUE TITLE
Vex-hugo theme changes not reflecting in local dev env? 

### ISSUE THREAD

**Issue by FickleLife** [themefisher/vex-hugo#16]
I have built a site off vex, made some changes (e.g. changed font of theme to Helvetica) and deployed to netlify and all looks good. 

When I try to launch my forked local repository with `hugo server` I get `Error: module "vex-hugo" not found; either add it as a Hugo Module or store it in "/xxxx/project/exampleSite/themes".: module does not exist`. 

I have cloned vex-hugo into /xxxx/ and then it launches with `hugo server --themesDir ../..` but it's using the theme in the /xxxx/vex-hugo folder, not the theme in /xxxx/project so it's not taking the styling. However netlify is fine. 

I'm new to hugo, any clues what's going on? Thanks

**Comment by developer-evan** [comment]
`cd exampleSite/`

then `hugo server --themesDir ../..`
