### ISSUE TITLE
How to add internal links to navigation bar?

### ISSUE THREAD

**Issue by tenpast** [themefisher/vex-hugo#17]
I would like to add navigation menu items to scroll to different areas of the current page instead of taking me to other pages. The config.toml file specifies these as:

[[menu.main]]
name = "About Us"
URL = "blog"
weight = 3

When I change the url to "#blog" to point to an internal link, the website does not compile with that hashtag, but a "/" gets inserted automatically.

How can I point to internal links from the navigation menu and once I get that working, should I add the internal <a> element into one of the html partials in the theme configuration?

Thank you for your help!

**Comment by developer-evan** [comment]
hey there, the menu item doesn't work like that, so you need to do some tweaks.

[[menu.main]]
name = "About Us"
URL = "https://yoursite.com#blog"
weight = 3

**Comment by tenpast** [comment]
Hi, yes thank you, I appreciate your help! This works, but makes the `config.toml` file clumsy if the `baseURL` ever needs to change. 

I was wondering if instead it would be possible to add an `if` statement in the `header.html` file that either checks for a `URL` that starts with a `#` or an extra definition in the .toml file, such as `internal-link = true`, to concatenate the `.baseURL` with the `.URL`. In this way there is only one place in the config file where the `baseURL` needs to be modified.

I looked at the `header.html` file but I don't understand exactly how that would work with the `absLangURL` to support the multi-language functionality.

**Comment by developer-evan** [comment]
Hey there, as you want, I made an update of this theme, and create a demo nav-item with #id. now you can download the theme and use it.

**Comment by tenpast** [comment]
Thank you for your help, I appreciate it!
