### ISSUE TITLE
Adding products doesn’t make them appear in the product list

### ISSUE THREAD

**Issue by arxdsilva** [themefisher/vex-hugo#20]
Hey guys,

I tried to sort it out for a bit but didn’t get much without messing around with the templates. Is there a better solution? Isn’t it structure related?

**Comment by mehedi-sharif** [comment]
@arxdsilva 
If you do not explain your issue it's hard to reply. Explain what kind of issue you are facing and where this issue is happening .
Thanks

**Comment by arxdsilva** [comment]
Hi Mehedi, I've launched it using netlify+forestry.io and tried to add a new product (or even modify a old one). 

When adding a new product it wont appear in the list of products and If I add a new photo to an existing product, It wont show on the site (eg: https://5f84f5c2e612cc00089be820--tender-euler-1ab8c8.netlify.app/products/#/)

On the link above the product listed as "buque com chololate" should have flowers in its image as I added to the forestry.io

**Comment by arxdsilva** [comment]
The previously created products use a "images" tag (that loads) that is a list of links and the [forestry.io struct](https://github.com/themefisher/vex-hugo/blob/0bd4c51c33ba829fae8a7a3a72f2da873a1e1bbc/exampleSite/.forestry/front_matter/templates/product.yml#L12) has a "image" tag that is a simple link that wont ever load to the site.

**Comment by developer-evan** [comment]
Hello @arxdsilva 

Thanks for your concern. It was a bug. We fixed it, now you can download the latest code.

Also if you like this template, a star to the repository would be incredible.
