### ISSUE TITLE
Add line breaks in homepage.yml

### ISSUE THREAD

**Issue by tenpast** [themefisher/vex-hugo#21]
Hi, I'm trying to add line breaks on a subtitle element on the homepage.yml file but cannot figure out how to force a line break. I have tried inserting <br />, <br>, \n, |

subtitle : "I want a line break here. <br> Thanks!"

Thank you for your help :)

**Comment by developer-evan** [comment]
Hello @tenpast 

can you please download the latest version and try `<br>` for line break? thank you.

**Comment by tenpast** [comment]
Yes, it works, thank you!
