### ISSUE TITLE
Cannot add Google Analytics to theme

### ISSUE THREAD

**Issue by tenpast** [themefisher/vex-hugo#22]
Hi Somrat, 

I tried adding Google Analytics by just adding the code in the correct variable in config.toml but I could not get it to work. Running google's tags extension it found 2 errors and one warning. I've tried to investigate and can see two references in head.html to google_analytics.html and google_analytics_async.html but cannot locate those files. Are they supposed to be bundled with the theme or is this a bug? What am I missing?

Thank you for your help. I've added you to an issue on my repo with a couple of screenshots to further illustrate the problem.

**Comment by tenpast** [comment]
OK, I read now that these are internal templates. One of the complaints from the tags extension was that the javascript code for Analytics was included twice in the template...do you think this is because of including both the analytics and the analytics_async template?

      {{ template "_internal/google_analytics.html" . }}
      {{ template "_internal/google_analytics_async.html" . }}

Should it be one or the other?

**Comment by davidsneighbour** [comment]
Hi @tenpast. Do you use the "old" way of Google Analytics? The config code needs to start with "UA-" for it to work. Hugo has recently added features to use the new Google Analytics code. If your latest version is 0.79.0 it might work now. If it still does not work please add what exactly you try to configure. 

The internal templates are hidden away in the hugo source code: https://github.com/gohugoio/hugo/blob/755d1ffe7a22d8ad83485240ff78cf25d501602f/tpl/tplimpl/embedded/templates/google_analytics.html

**Comment by tenpast** [comment]
Hi @davidsneighbour, 

Indeed, I was trying to use the "new" way of Google Analytics without knowing so. My config code started with ```G-```. I have now created a new property with the ```UA-``` code and added that to the site. I will wait 24 hours and see if it starts tracking. I have checked with Google Tag Assistant and there are no errors now, so I am hopeful that will do the trick

I'm using version 0.78.2 for the record.

I also wonder what the difference is between ```google_analytics.html``` and ```google_analytics_async.html``` templates. I removed the async and that got rid of the tracking information being found twice on the page as Google Tag Assistant extension had complained.

Thank you for your help!

**Comment by davidsneighbour** [comment]
The async is only the way the javascript is loaded. Using it will lead to GA loading "a little bit later". The non-async way loads the JS at the point where it is added to the code and might block rendering or styles being applied. The async way is better (for page speed and user experience) but might miss out some microseconds before it's loaded. I normally use async.

**Comment by tenpast** [comment]
That's interesting. I think I'll use async as well in that case. Thanks again for the valuable help and information! :)
