### ISSUE TITLE
Remove the # in all URLs

### ISSUE THREAD

**Issue by davidsneighbour** [themefisher/vex-hugo#23]
There is a request open in the Hugo Discourse about the # that is added to all URLs. I tried to find what script does this but failed... Any idea? Is there a way to disable the #? It does not seem to have any function further down the road.

https://discourse.gohugo.io/t/hugo-vex-theme-remove-from-url/29624

**Comment by developer-evan** [comment]
The `#` is coming from snipcart, I see that the latest version of snipcart does not add a hash in the URL. so try to update the snipcart to the latest version. Thank you
