### ISSUE TITLE
Open links in new tab?

### ISSUE THREAD

**Issue by tenpast** [themefisher/vex-hugo#24]
Hi, I'm trying to open some links from homepage.yml in a new tab. Example

In homepage.yml section: 
```content : " Some content [link](https://example.com] more content"```

In partial.html:
````{{ .content | markdownify }}````

I have tried the `.../layouts/_default/_markup/render-link.html` workaround for Goldmark, but it does not work when passing the content through the short code as done in vex-hugo theme.

Thanks for your help!

**Comment by somratpro** [comment]
Hello @tenpast 

Try `<a href="https://examplesite.com" target="_blank">link</a>` this

**Comment by tenpast** [comment]
Hi @somratpro 

Thank you for your response.

How do I escape the quotation marks (")? Otherwise when the .yml file is parsed by Hugo it will interpret the quotation mark as part of the yaml structure and mess up the file:

```content : " Some content <a href="https://examplesite.com" target="_blank">link</a>  more content"

**Comment by somratpro** [comment]
you can use single 'quote'

**Comment by tenpast** [comment]
Yes, that worked, I used a single quote for the yaml content delimiter.

Thank you :)

**Comment by tenpast** [comment]
I'm adding this as a follow-up in case this question ever comes up again. Escaping single quotes has the disadvantage that any use of single quotes then becomes a problem (example, apostrophes). The way to make the above work with double quotes is to escape the double quotes with a back-slash (like so: \"). Then the content section looks something like this:

```content : " Some content <a href=/"https://examplesite.com/" target=/"_blank/">link</a> more content"```
