### ISSUE TITLE
Product Slider isn't displaying when language direction is RTL

### ISSUE THREAD

**Issue by houmie** [themefisher/vex-hugo#26]
Hello,

To simplify the steps, lets give French a Right-To-Left direction. But the same happens when using Persian or Arabic.

1) Download the Vex-hugo https://github.com/themefisher/vex-hugo.git
2) vim ./vex-hugo/exampleSite/config.toml
3) Scroll down to French and add ```LanguageDirection = "rtl"```
4) Open ```layouts/_default/baseof.html``` and change the html line to 
```
<html lang="{{ with site.Language.Lang }}{{ . }}{{ else }}en-US{{ end }}" dir="{{ site.Language.LanguageDirection | default "ltr" }}">
```

Because the current one is wrong.  It doesn't inject the language and direction. (That's another bug that you can fix if you like. But the real issue is below)

5) Open Products, click on a watch. As you see there is no slider.

You can open the source code and change ```<html lang="fr" dir="rtl">``` to ```<html lang="fr" dir="ltr">``` and the slider appears again. :-)

I think this is a bug in the javascript, but I'm not sure.

<img width="1225" alt="Screenshot 2021-01-11 at 08 22 37" src="https://user-images.githubusercontent.com/1832933/104159570-7aef8380-53e7-11eb-9c98-3c9dbcdeae4d.png">

Thanks,
Houman

**Comment by somratpro** [comment]
Hello @houmie 

we are using slick slider in this theme, so when you are shifting the site from RTL, you also need to change the direction from slick slider. Go to `assets/script.js` and add this in slick slider settings `rtl: true,`

**Comment by houmie** [comment]
Hello @somratpro 
Thank you. I got it working like this:

I duplicated ```assets/script.js``` as ```assets/script.ar.js``` 

then 

```
<!-- Main Script -->
{{ if eq site.Language.Lang "ar" }}
{{ $script := resources.Get "js/script.ar.js" }}
<script src="{{ $script.Permalink }}"></script>
{{ else }}
{{ $script := resources.Get "js/script.js" }}
<script src="{{ $script.Permalink }}"></script>
{{ end }}
```

Now it works.
