### ISSUE TITLE
Switching language and clicking on menu item jumps back to English

### ISSUE THREAD

**Issue by houmie** [themefisher/vex-hugo#27]
Hello,

1) Please edit ```exampleSite/data/fr/homepage.yml```

Change
```
testimonial:
  enable : true
  title : "Watch Review"
```

to 

```
testimonial:
  enable : true
  title : "French Review"
```

2) Go back to homepage
3) Switch to French
4) Scroll down, until you see the review displaying "French Review"
5) Now click on Review on the menu.

<img width="1078" alt="Screenshot 2021-01-11 at 08 44 27" src="https://user-images.githubusercontent.com/1832933/104160683-6dd39400-53e9-11eb-83a2-1d365037eba7.png">

The language switches back to English and the review displays ```Watch Review``` instead of ```French Review```.

This should really just scroll down to the same French page, not switching it back to English.

Many Thanks,
Houman

**Comment by somratpro** [comment]
Hello @houmie 

Thanks for your concern, this issue has been fixed. please download the latest code and enjoy.

Also if you like this template, a star to the repository would be incredible.

**Comment by houmie** [comment]
Thank you for being so active.  I love this project and have given it a star.

I confirm that the issue has been resolved.
