### ISSUE TITLE
"Order couldn’t be processed" message by snipcart in test mode

### ISSUE THREAD

**Issue by nextcloudbox** [themefisher/vex-hugo#28]
Hello,
I use snipcart in test mode. I not modify URL, just created my products. When I want to buy an article, I have the message : "Order couldn’t be processed"
![url](https://i.ibb.co/jbF3vY4/Capture.jpg)
How can I fix it ?
Thanks.

**Comment by somratpro** [comment]
Hello @nextcloudbox 

Thanks for using this template. This issue is not on our end, please contact snipcart to resolve this issue. thank you
