### ISSUE TITLE
"Domain crawling error" message by snipcart 

### ISSUE THREAD

**Issue by nextcloudbox** [themefisher/vex-hugo#29]
Hello,
I use snipcart in test mode. I not modify URL, just created my products and added. When I want to buy an article, I have the message : "Domain crawling error".
![url](https://i.ibb.co/jbF3vY4/Capture.jpg)
I already added my domain on snipcart :
![url](https://i.ibb.co/t4whJ4H/Capture2.jpg)
How can I fix it ?
Thanks.

**Comment by somratpro** [comment]
Hello @nextcloudbox

Thanks for using this template. This issue is not on our end, please contact snipcart to resolve this issue. thank you
