### ISSUE TITLE
stylesheet.css

### ISSUE THREAD

**Issue by shawngraham** [themefisher/vex-hugo#3]
Hi,

I was finding that when I used this theme, there was an issue with the stylesheet causing the different elements of the page to overlap when viewed on a phone or tablet- features being printed overtop the promo etc. 

changing the .hero-area from `vh` to `%` solved it, eg:

```
.hero-area {
  height: 90%;
```

Cheers

**Comment by orlsend** [comment]
Sorry to bother you, I am using the non-hugo version of this template. While doing the suggested does help, it still a bit wonky. 
![screenshot_2018-10-28-00-39-14](https://user-images.githubusercontent.com/8900265/47612523-1637f080-da4a-11e8-9b94-1c313d15e71c.jpg)

**Comment by mehedi-sharif** [comment]
@orlsend  Please download the html version from our website https://themefisher.com/products/vex-bootstrap4-product-landing-page-website-template/ . We fixed all the issues in latest release .
Thanks
