### ISSUE TITLE
Borken URL on Home button when I am in french

### ISSUE THREAD

**Issue by nextcloudbox** [themefisher/vex-hugo#32]
Hello,
When I use the french version of the site and after a click on `Home` button, I am redirected on :
`https://mywebsite.netlify.app/fr/the-where-i-was/fr/`
and not 
`https://mywebsite.netlify.app/fr/`
How to fix it ?
Thanks.

**Comment by somratpro** [comment]
Hello @nextcloudbox 

This should not be happening, I check it on my localhost, and it works perfectly. so can you share any live URL with me?

**Comment by nextcloudbox** [comment]
Hello,
The URL is on my repository.

**Comment by mehedi-sharif** [comment]
Hello @nextcloudbox ,
It seems that you configured the theme in wrong way and , "The URL is on my repository." we are not a detective team to figure out your repository . I am closing this issue and suggest you try the installation from beginning 
Thanks

**Comment by nextcloudbox** [comment]
Hello,
Sorry for the mistake, I think it was on my repository :)
This is the URL : https://nextcloudbox.netlify.app
Thanks for your help.
