### ISSUE TITLE
Contact information logo is present even if the value is empty

### ISSUE THREAD

**Issue by nextcloudbox** [themefisher/vex-hugo#33]
Hello,
I just set the location in the contact page, not the phone and mail. The problem is the logo are not removed : 
![Logo not removed](https://i.ibb.co/rFmDgXz/Capture.jpg)
How to fix it ?
Thanks.

**Comment by somratpro** [comment]
Hello @nextcloudbox 

This issue has been fixed. please download the latest code. thank you
