### ISSUE TITLE
Multilingual only applies to post content?

### ISSUE THREAD

**Issue by maggie0002** [themefisher/vex-hugo#34]
I have been trying to implement the multilingual features of the template, and it only appears to apply to the post content. I can't seem to get the navigation menu to be multilingual. Am I missing something here?

**Comment by nextcloudbox** [comment]
Same problem, my menu is in french when I select french version but when I select English version, the menu stays in french.

**Comment by maggie0002** [comment]
Ideally the menu names would be included in the homepage.yml so it can all be translated in one file?

**Comment by somratpro** [comment]
Hello there, 

Did you check this doc https://gohugo.io/content-management/multilingual/#menus
