### ISSUE TITLE
The structure of the web site URL don't respects the Snipcart prerequisite

### ISSUE THREAD

**Issue by nextcloudbox** [themefisher/vex-hugo#35]
Hello,
I can't validate a transaction with Snipcart because the URL don't respects the structure : 
![Structure](https://i.ibb.co/tJc77kq/Structure.png)
According the documentation : https://docs.snipcart.com/v3/setup/order-validation
Snipcart needs a structure like that : `https://mysite.com/products/1` and I have `https://mysite.netlify.app/products/product-6/`
Also, Snipcart needs a metadata : `data-item-url` and I haven't that.

Could you check where is my error on the configuration of the site ? This is the URL : 
https://nextcloudbox.netlify.app/products/
This is the repo : https://github.com/nextcloudbox/nextcloudbox
Thanks.

**Comment by somratpro** [comment]
Hello @nextcloudbox 

Thanks for choosing our template, actually we have this metadata, see the screenshot. I think you need to contact snipcart for this issue.
![image](https://user-images.githubusercontent.com/37659754/107841806-5cb2e400-6de8-11eb-9eb0-b79aac5ffaf1.png)

**Comment by nextcloudbox** [comment]
Hello,
This is the SnipCart answer : 

> Hi there,
> 
> 
> You get this error because order validation (https://docs.snipcart.com/v3/setup/order-validation) fails. You will find more information on the product causing the error in de developer logs (https://app.snipcart.com/dashboard/logs).
> First, make sure the data-item-url points to the page with the Snipcart button if you are using the HTML crawler or to the product definition if you are using the JSON crawler.
> 
> If you are using a relative URL, make sure you set up the default domain (https://app.snipcart.com/dashboard/account/domains). This URL needs to be publicly accessible. If you want to test in local development, you can use a tool like ngrok (https://snipcart.com/blog/develop-a-snipcart-powered-website-locally-using-ngrok).
> 
> Another important aspect is that the Snipcart button cannot be added dynamically (i.e., via javascript or a front-end framework like Vue). If this is your case, then the JSON crawler would be more appropriate for you (https://docs.snipcart.com/v3/setup/order-validation#json-crawler).
> 
> 
> Hope this helps,
> Cheers

For information, this is logs I have and I send them. I am waiting for the answer : 

```
Feb 12 14:20:39 | Impossible  to validate items for order '534a3e32-9683-43cc-abef-5ec15337d1bf'.  Please make sure the URL is valid, we suggest you take a look at our  Security documentation  http://docs.snipcart.com/getting-started/security) for more information.
-- | --
Feb 12 14:20:39 | Relative  URL '/en/products/product-2/' cannot be used as item URL because the  account's main domain is not set. To fix it, go to your merchant  dashboard  https://app.snipcart.com/dashboard/account/domains) and fill the default website domain section. We suggest you take a look at the Order Validation section of our documentation  https://docs.snipcart.com/v3/setup/order-validation) to understand how validation works.
Feb 12 14:20:39 | Validating item with id 'nextcloudbox-2-to__235' located at '/en/products/product-2/' on domain ''.
Feb 12 14:17:30 | Impossible  to validate items for order '534a3e32-9683-43cc-abef-5ec15337d1bf'.  Please make sure the URL is valid, we suggest you take a look at our  Security documentation  http://docs.snipcart.com/getting-started/security) for more information.
Feb 12 14:17:30 | Relative  URL '/products/product-8/' cannot be used as item URL because the  account's main domain is not set. To fix it, go to your merchant  dashboard  https://app.snipcart.com/dashboard/account/domains) and fill the default website domain section. We suggest you take a look at the Order Validation section of our documentation  https://docs.snipcart.com/v3/setup/order-validation) to understand how validation works.
Feb 12 14:17:30 | Validating item with id 'nextcloudbox-1-to__195' located at '/products/product-8/' on domain ''.
Feb 03 21:29:59 | Impossible  to validate items for order '534a3e32-9683-43cc-abef-5ec15337d1bf'.  Please make sure the URL is valid, we suggest you take a look at our  Security documentation  http://docs.snipcart.com/getting-started/security) for more information.
Feb 03 21:29:59 | Relative  URL '/products/product-6/' cannot be used as item URL because the  account's main domain is not set. To fix it, go to your merchant  dashboard  https://app.snipcart.com/dashboard/account/domains) and fill the default website domain section. We suggest you take a look at the Order Validation section of our documentation  https://docs.snipcart.com/v3/setup/order-validation) to understand how validation works.
Feb 03 21:29:59 | Validating item with id 'nextcloudbox-2-to__235' located at '/products/product-6/' on domain ''.

```

**Comment by somratpro** [comment]
Hello @nextcloudbox 

remove this line from your netlify settings
https://github.com/themefisher/vex-hugo/blob/e11141f35a75ad06cfe7afa9550253674c019000/netlify.toml#L8

and add baseURL perfectly on your config.toml file.  it might solve your problem.
