### ISSUE TITLE
Improve the Google PageSpeed Insights score

### ISSUE THREAD

**Issue by nextcloudbox** [themefisher/vex-hugo#36]
Hello,
I test my website with PageSpeed Insights : https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=https%3A%2F%2Fnextcloudbox.netlify.app%2F

The result is bad (47/50) : 
![https://i.ibb.co/RShhw49/score.png](https://i.ibb.co/RShhw49/score.png)

The JavaScript delivered by the CDN is very low to load and the recommendation is to `Remove unused JavaScript`.
Is it possible to set the loading in last of the entire web site to improve the PageSpeed Insights score ?

Moreover, an other recommendation is to `Eliminate render-blocking resources` which include the following : 
```
/css?family=Droid+Serif:400%7cJosefin+Sans:300,400,600,700(fonts.googleapis.com)
…bootstrap/bootstrap.min.css(nextcloudbox.netlify.app)
…themefisher-font/themefisher-font.min.css(nextcloudbox.netlify.app)
…slick/slick.min.css(nextcloudbox.netlify.app)
…default/snipcart.css(cdn.snipcart.com)
/scss/style.min.css(nextcloudbox.netlify.app)
...
```
Another recommendation is to : 
- Ensure text remains visible during webfont load
- Does not use passive listeners to improve scrolling performance
- Serve static assets with an efficient cache policy

Could you verify each Google recommendation on my web site and improve the theme to optimize it?
The modifications you will implements will optimize also others people theme.
Thanks.

**Comment by sojonatgithub** [comment]
Hey @nextcloudbox 
We provide custom service to improve page speed.
You can contact us [(mehedi@themefisher.com)](mailto:mehedi@themefisher.com) for more information about the service.

**Comment by nextcloudbox** [comment]
Hello @sojonatgithub 
Thank you for your purpose. However, I am not searching a service to SEO. What I am trying to explain is that the web site is not optimized. For example, this part of the source code : 
```
  <!-- plugins -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid&#43;Serif:400%7cJosefin&#43;Sans:300,400,600,700 ">
  <link rel="stylesheet" href="https://nextcloudbox.netlify.app/plugins/bootstrap/bootstrap.min.css ">
  <link rel="stylesheet" href="https://nextcloudbox.netlify.app/plugins/themefisher-font/themefisher-font.min.css ">
  <link rel="stylesheet" href="https://nextcloudbox.netlify.app/plugins/slick/slick.min.css ">
  <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.css ">
```
Should be placed at the end of the page to be load in last and not block rendering. This kind of optimization is normally native on a theme. It's a classic feature to improve speed of the site. Could you change it on the theme to optimize it or I do it manually on my web site ?
Thanks.

**Comment by somratpro** [comment]
Hello @nextcloudbox 

Currently, we have a lot of tasks to do, so we are not going to update this theme in a while. it will be great if you do it manually and also create a PR for vex theme users.
