### ISSUE TITLE
Error sitemap.xml with the Google Search Console

### ISSUE THREAD

**Issue by nextcloudbox** [themefisher/vex-hugo#37]
Hello,
I want to send my sitemap to Google Search Console but when I send it, I have an error because the sitemap.xml is not valid according to Google. It's not a problem of SEO but validity of sitemap.xml file : 
![https://i.ibb.co/Vpp5Sxs/sitemap-not-valid.png](https://i.ibb.co/Vpp5Sxs/sitemap-not-valid.png)
This is the details : 
![https://i.ibb.co/DCtHjMR/sitemap-details.png](https://i.ibb.co/DCtHjMR/sitemap-details.png)
This is the sitemap generated by the theme :
https://nextcloudbox.netlify.app/fr/sitemap.xml
https://nextcloudbox.netlify.app/en/sitemap.xml

**Comment by somratpro** [comment]
Hello @nextcloudbox 

a sitemap is not customizable, because Hugo generates it automatically, I suggest you discuss it on Hugo forum. Thank you
