### ISSUE TITLE
vex-hugo don't generate a robot.txt file

### ISSUE THREAD

**Issue by nextcloudbox** [themefisher/vex-hugo#38]
Hello,
Why vex-hugo don't generate a `robot.txt `file with inside URL of the sitemap ?
The content normally should be : 
```
Sitemap: http://the_address_of_the_site/sitemap.xml
User-agent:*
Disallow:
```

Could you add this functionality ? If you can't, please can you tell me how can I put it ?
Thanks.

**Comment by somratpro** [comment]
hello there, 

Please follow this official doc to do this https://gohugo.io/templates/robots/
