### ISSUE TITLE
How can I disable the snipcart globally?

### ISSUE THREAD

**Issue by tonyho** [themefisher/vex-hugo#42]
Thanks for sharing the wonderful theme.
We want to disable the snipcart globally, like the `cart` icon in menu and the `add to cart` button, is there any parameter to control the enable/disable this feature?

**Comment by somratpro** [comment]
Hello @tonyho,

Thanks for choosing our template, I have added an option to disable snipcart. you can found it in config.toml file. 

You can share your live site, we will add it to our showcase. Also if you like this template, a star to the repository will appreciate us.
