### ISSUE TITLE
How do I customize the payment gateway part in Vex?

### ISSUE THREAD

**Issue by touhidurrr** [themefisher/vex-hugo#45]
I want to add some other payment method and customize the client details fields. How do I do that?

**Comment by mehedi-sharif** [comment]
which payment method do you want to use ? If they have integration with static site you can add them by following their documentation

**Comment by touhidurrr** [comment]
I am actually new on hugo. I want to know how to customise your theme and add some additional scripts on the gateway part.

The things I want to do.

1. Remove Credit card Gateway.
2. Edit the Client Info Fields.
3. Add the logo of a local gateway and inject some scripts to make the site able to use it.

**Comment by touhidurrr** [comment]
Also what country are you from? You look like Bangladeshis.

**Comment by mehedi-sharif** [comment]
Then I suggest you learn hugo first then start working with the themes . 
Thanks
