### ISSUE TITLE
App Store Buttons

### ISSUE THREAD

**Issue by cyberaxcess** [themefisher/vex-hugo#46]
Hi,

Thank you for a great theme!

How can I go about adding buttons on the page(s) using the official Play Store and App Store graphics (with links to the stores) on the home page in the different sections?

I would like to do this in the banner section and in the promo section.

Thanks!

**Comment by cyberaxcess** [comment]
Okay, I think I figure this out...

I used the short code: 
`[![Example image](/images/appstore.svg)](https://www.apple.com)`
(with the correct links of course).

If this is the best way, you can close this, if you have any other suggestions or if its different in other places then please let me know!

Thanks.

**Comment by tfsomrat** [comment]
Hey @cyberaxcess 
Thanks for using our theme. You found the right way. so I am closing this issue. if you have any other queries, then create a new issue.
