### ISSUE TITLE
Theme does not compile correctly

### ISSUE THREAD

**Issue by rnucuta** [themefisher/vex-hugo#5]
I cannot get the hugo theme to display properly when I run `hugo server`
Essentially, all I have done is clone the theme into the themes folder, and copied the example site config.toml file over to the sites main directory. When I do so, the webpage looks like this. How do I fix this?
![Capture](https://user-images.githubusercontent.com/44931708/61431078-decbe580-a8f1-11e9-8200-104ec2123964.PNG)

**Comment by Somrat37** [comment]
It looks like css is missing, i just download and run this template on my localhost, it's working perfectly, can you please recheck every steps? or you can follow this [video tutorial](https://www.youtube.com/watch?v=jrkvirglgaQ)

**Comment by rnucuta** [comment]
Thank you so much, that fixed it!
